version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/default.conf
    depends_on:
      - fastapi
