version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    expose:
      - 8000

  nginx:
    restart: always
    image: nginx:1.23-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi

volumes:
    static_volume: { }
