name: CD Pipeline for FastAPI Application

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Deploy only runs after the tests are successful
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH key for EC2 access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Pull latest code and restart app on EC2
        run: |
          # Allow git to work with the directory safely
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            git config --global --add safe.directory /home/ubuntu/HNGProjects/fastapi-book-project
            cd /home/ubuntu/HNGProjects/fastapi-book-project
            git pull origin main
            docker-compose down
            docker-compose up -d
          EOF
