name: CI Pipeline for FastAPI Application

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main  # Run tests only on PRs targeting main

# This job runs tests when a PR is opened or updated
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Test SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "SSH Connection Successful!"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest tests/ --exitfirst --disable-warnings

  auto-merge:
    needs: test  # Only run if tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Auto-Merge PR
        uses: pascalgn/automerge-action@v0.15.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
          required-status-checks: "test"  # Only merge if tests pass

