name: CI Pipeline for FastAPI Application

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main  # Run tests only on PRs targeting main

# This job runs tests when a PR is opened or updated
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Test SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "SSH Connection Successful!"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest tests/ --exitfirst --disable-warnings

#  automerge:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#      pull-requests: write
#    steps:
#      - id: automerge
#        name: automerge
#        uses: "pascalgn/automerge-action@v0.16.4"
#        env:
#          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  automerge:
    runs-on: ubuntu-latest
    needs: test  # Ensures automerge only runs if 'tests' job passes
    if: success() # Only runs if all previous jobs (tests) succeed
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Add "automerge" Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge

      - id: automerge
        name: Automerge PR
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          merge-method: merge  # Options: 'merge', 'squash', 'rebase'
          labels: "automerge"  # Ensures PR has this label before merging
          required-status-checks: "test"  # Ensures 'tests' job passed before merging
